; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs=m5stack-core2

[env]
platform = espressif32 @ 5.2.0
framework = arduino
lib_ldf_mode = deep
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
build_type = debug
monitor_filters =  esp32_exception_decoder
                   time
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw
	-D SDFAT_FILE_TYPE=3
; SdFat #define SDFAT_FILE_TYPE 3   // SDFAT_FILE_TYPE = 0 for SdFat/File as defined in SdFatConfig.h,
; 1 for FAT16/FAT32, 2 for exFAT, 3 for FAT16/FAT32 and exFAT.
	-D ENABLE_DEDICATED_SPI=0
; SdFat SHARED_SPI / ENABLE_DEDICATED_SPI 0 is choosen because SD card and TFT are sharing one SPI bus
    -D USE_HARDWARE_BLE=0
; 0 BLE data reception is performed on SoftwareSerial, 1 Use hardwareSerial
upload_speed = 1500000
lib_deps = 
	mikalhart/TinyGPSPlus@^1.0.3
	ambientdatainc/Ambient ESP32 ESP8266 lib
	m5stack/M5Unified
	tzapu/WiFiManager @ ^2.0.17
	paulstoffregen/Time @ ^1.6.1
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    plerup/EspSoftwareSerial @ ^8.2.0
    greiman/SdFat @ ^2.2.3
	
[env:m5stack-core2]
board = m5stack-core2

[env:m5stack-basic]
board = m5stack-grey
board_build.partitions = huge_app.csv
